name: partyshark_server_support
version: 0.0.1
description: Generic support libraries developed parallel to the PartyShark API server.
author: Nick Reid <nreid26@uwo.ca>
#homepage: https://www.example.com

environment:
    sdk: '^1.0.0'

dependencies:
    logging: '^0.11.0'

dev_dependencies:
    test: '>=0.12.0 <0.13.0'