name: partyshark_server
version: 0.0.1
description: The API server of the PartyShark web-app.
author: Nick Reid <nreid26@uwo.ca>
#homepage: https://www.example.com

environment:
    sdk: '^1.0.0'

dependencies:
    resource: '^1.1.0'
    logging: '^0.11.0'

dev_dependencies:
    test: '>=0.12.0 <0.13.0'